extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const MacroObject ssl_area_1_macro_objs[];
extern Lights1 ssl_dl_f3dlite_material_lights;
extern Lights1 ssl_dl_Leathal_Quicksand_lights;
extern Lights1 ssl_dl_Normal_Sand_lights;
extern Lights1 ssl_dl_Platform_lights;
extern u8 ssl_dl_bob_textures_03000_rgba16_i8[];
extern u8 ssl_dl__7_rgba16_ci8[];
extern u8 ssl_dl__7_rgba16_ci8_pal_rgba16[];
extern u8 ssl_dl_bob_textures_08000_rgba16_ci8[];
extern u8 ssl_dl_bob_textures_08000_rgba16_ci8_pal_rgba16[];
extern u8 ssl_dl_bob_textures_02800_rgba16_ci8[];
extern u8 ssl_dl_bob_textures_02800_rgba16_ci8_pal_rgba16[];
extern Vtx ssl_dl_Cube_mesh_layer_1_vtx_0[186];
extern Gfx ssl_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_0[174];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_1[490];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_2[24];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_2[];
extern Gfx mat_ssl_dl_f3dlite_material[];
extern Gfx mat_ssl_dl_Leathal_Quicksand[];
extern Gfx mat_revert_ssl_dl_Leathal_Quicksand[];
extern Gfx mat_ssl_dl_Normal_Sand[];
extern Gfx mat_revert_ssl_dl_Normal_Sand[];
extern Gfx mat_ssl_dl_Platform[];
extern Gfx mat_revert_ssl_dl_Platform[];
extern Gfx ssl_dl_Cube_mesh_layer_1[];
extern Gfx ssl_dl_Plane_mesh_layer_1[];
extern Gfx ssl_dl_material_revert_render_settings[];
