extern const GeoLayout ssl_area_1_geo[];
extern const GeoLayout ssl_area_1[];
extern const Collision ssl_area_1_collision[];
extern const MacroObject ssl_area_1_macro_objs[];
extern const GeoLayout ssl_area_2_geo[];
extern const GeoLayout ssl_area_2[];
extern const Collision ssl_area_2_collision[];
extern const MacroObject ssl_area_2_macro_objs[];
extern Lights1 ssl_dl_f3dlite_material_v5_lights;
extern Lights1 ssl_dl_Castle_lights;
extern Lights1 ssl_dl_Leathal_Quicksand_lights;
extern Lights1 ssl_dl_Normal_Sand_lights;
extern Lights1 ssl_dl_Platform_lights;
extern Lights1 ssl_dl_Water_lights;
extern Lights1 ssl_dl_texture_test_lights;
extern u8 ssl_dl_bob_textures_03000_rgba16_i8[];
extern u8 ssl_dl_bob_textures_0A800_rgba16_rgba16[];
extern u8 ssl_dl__7_rgba16_ci8[];
extern u8 ssl_dl__7_rgba16_ci8_pal_rgba16[];
extern u8 ssl_dl_bob_textures_08000_rgba16_ci8[];
extern u8 ssl_dl_bob_textures_08000_rgba16_ci8_pal_rgba16[];
extern u8 ssl_dl_bob_textures_02800_rgba16_ci8[];
extern u8 ssl_dl_bob_textures_02800_rgba16_ci8_pal_rgba16[];
extern u8 ssl_dl_segment2_11C58_rgba16_png_001_ci8[];
extern u8 ssl_dl_segment2_11C58_rgba16_png_001_ci8_pal_rgba16[];
extern u8 ssl_dl_bob_textures_05000_rgba16_rgba16[];
extern u8 ssl_dl_wf_textures_05800_rgba16_png_001_ci8[];
extern u8 ssl_dl_wf_textures_05800_rgba16_png_001_ci8_pal_rgba16[];
extern Vtx ssl_dl_Cube_mesh_layer_1_vtx_0[200];
extern Gfx ssl_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Cube_001_mesh_layer_1_vtx_0[190];
extern Gfx ssl_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Cube_002_mesh_layer_1_vtx_0[42];
extern Gfx ssl_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Cube_003_mesh_layer_1_vtx_0[42];
extern Gfx ssl_dl_Cube_003_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Cube_004_mesh_layer_1_vtx_0[42];
extern Gfx ssl_dl_Cube_004_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Cube_005_mesh_layer_1_vtx_0[42];
extern Gfx ssl_dl_Cube_005_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Cylinder_mesh_layer_1_vtx_0[424];
extern Gfx ssl_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Cylinder_001_mesh_layer_1_vtx_0[424];
extern Gfx ssl_dl_Cylinder_001_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_0[142];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_1[819];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_1[];
extern Vtx ssl_dl_Plane_mesh_layer_1_vtx_2[24];
extern Gfx ssl_dl_Plane_mesh_layer_1_tri_2[];
extern Vtx ssl_dl_Plane_001_mesh_layer_5_vtx_0[4];
extern Gfx ssl_dl_Plane_001_mesh_layer_5_tri_0[];
extern Vtx ssl_dl_Cube_006_mesh_layer_1_vtx_0[216];
extern Gfx ssl_dl_Cube_006_mesh_layer_1_tri_0[];
extern Vtx ssl_dl_Cube_006_mesh_layer_5_vtx_0[24];
extern Gfx ssl_dl_Cube_006_mesh_layer_5_tri_0[];
extern Gfx mat_ssl_dl_f3dlite_material_v5[];
extern Gfx mat_ssl_dl_Castle[];
extern Gfx mat_ssl_dl_Leathal_Quicksand[];
extern Gfx mat_revert_ssl_dl_Leathal_Quicksand[];
extern Gfx mat_ssl_dl_Normal_Sand[];
extern Gfx mat_revert_ssl_dl_Normal_Sand[];
extern Gfx mat_ssl_dl_Platform[];
extern Gfx mat_revert_ssl_dl_Platform[];
extern Gfx mat_ssl_dl_Water[];
extern Gfx mat_revert_ssl_dl_Water[];
extern Gfx mat_ssl_dl_Inside_Pyramid[];
extern Gfx mat_revert_ssl_dl_Inside_Pyramid[];
extern Gfx mat_ssl_dl_texture_test[];
extern Gfx mat_revert_ssl_dl_texture_test[];
extern Gfx ssl_dl_Cube_mesh_layer_1[];
extern Gfx ssl_dl_Cube_001_mesh_layer_1[];
extern Gfx ssl_dl_Cube_002_mesh_layer_1[];
extern Gfx ssl_dl_Cube_003_mesh_layer_1[];
extern Gfx ssl_dl_Cube_004_mesh_layer_1[];
extern Gfx ssl_dl_Cube_005_mesh_layer_1[];
extern Gfx ssl_dl_Cylinder_mesh_layer_1[];
extern Gfx ssl_dl_Cylinder_001_mesh_layer_1[];
extern Gfx ssl_dl_Plane_mesh_layer_1[];
extern Gfx ssl_dl_Plane_001_mesh_layer_5[];
extern Gfx ssl_dl_Cube_006_mesh_layer_1[];
extern Gfx ssl_dl_Cube_006_mesh_layer_5[];
extern Gfx ssl_dl_material_revert_render_settings[];
